name: build and release pkg

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # ${{steps.tag.outputs.tag}}
    - uses: dawidd6/action-get-tag@v1
      id: tag

    - uses: actions/setup-go@v2
      with:
        go-version: '1.19'
    - name: Setup Golang caches
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}

    - name: Build
      env:
        CGO_ENABLED: 0
        GOARCH: amd64
        GOOS: linux
        GO111MODULE: on
      run: |
        make release

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: "👏🏻 ${{steps.tag.outputs.tag}}"
        files: dist/*.tar.gz
